# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

CONFIG_ZMK_KEYBOARD_NAME="Stainless"

#Experimental BT Connectivity 
#CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enables RGB functionality (Uncomment lines below to enable.)
#CONFIG_ZMK_RGB_UNDERGLOW=y
#CONFIG_WS2812_STRIP=y,
#config for said strip of rgb 
#CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
#CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=245
#CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
#CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=15

#disable backlight (just in case)
CONFIG_ZMK_BACKLIGHT=n

#zmkstudio?
#CONFIG_ZMK_STUDIO_LOCKING=y

#Rotary Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_POINTING=y

#Config to use dedicated thread for UI updates
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
#Stack size for the UI thread (if it must be adjusted)
#CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2048
#Priority for the UI thread
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=10


#Screen Settings

#Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=yes
#Locks display update tasks to montior refresh rate
#CONFIG_ZMK_DISPLAY_TICK_PERIOD_MS=33
#idles oled on pasts screen
#CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
#custom status screen 
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
#CONFIG_NICE_EPAPER_ON=n
#CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_WINDOWS=y
#CONFIG_NICE_OLED_WIDGET_LAYER=y
#CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y

#Right side screen
#CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_IDLE=y
#CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_SLEEP=y
#CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=n

#Left side screen

#try this
#CONFIG_NICE_OLED_WIDGET_RAW_HID=y

#bluetooth enhanced 
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

#sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_PM_SOFT_OFF=y
